### ISSUE TITLE
Feature check database consistency  (remove non existing file on disk)

### ISSUE THREAD

**Issue by gaelL** [guits/pastefile#48]
It could be good to have a cli tool to check that all file in the DB are existing on disk.
And if not, clean them from the DB.

Could be a script that we can call manually or in cron to clean entries in the DB.

**Comment by gaelL** [comment]
It also could be a new function : `check_db_consistency` that we call only on `post_file` for exemple.

**Comment by guits** [comment]
implemented in 4679081
