### ISSUE TITLE
Split app.py into smaller files

### ISSUE THREAD

**Issue by gaelL** [guits/pastefile#50]
I proposed : 
- `app.py` for api https://github.com/guits/pastefile/blob/master/pastefile/app.py#L209-L265
- `controller.py` for methode that do actions https://github.com/guits/pastefile/blob/master/pastefile/app.py#L70-L206
- `utils.py` for all generic tools https://github.com/guits/pastefile/blob/master/pastefile/app.py#L43-L67

Also rename some method to a more explicite name : https://github.com/guits/pastefile/blob/master/pastefile/app.py#L224-L229

For exemple :

```
get_or_delete_file_view
    delete_file()
    get_file()
```

If you are ok with that, I propose to implement that, just give me a GO when it should not impact code that you havn't merged yet

**Comment by guits** [comment]
let's go :+1:
