### ISSUE TITLE
jsonDB save need to switch to atomic save

### ISSUE THREAD

**Issue by gaelL** [guits/pastefile#55]
- http://stackoverflow.com/questions/2333872/atomic-writing-to-file-with-python

The `save` write the file. If we kill the process during the write, we will have a corrupted db.

It should be better to write a tmp file. And then rename it.

**Comment by gaelL** [comment]
It will also avoid read only use of the database to load just a part of the db.

**Comment by guits** [comment]
implemented in f816c69
